name: pdx-exomeseq
channels:
- r
- bioconda
- conda-forge
dependencies:
- pandas=0.18.0
- r::r-tidyverse=1.1.1
- r::r-devtools=1.13.3
- bioconda::bioconductor-rsamtools=1.28.0
- bioconda::bioconductor-genomicranges=1.28.6
- bioconda::bioconductor-genomicalignments=1.10.0
- bioconda::bwa=0.7.16
- bioconda::samtools=0.1.16
- bioconda::picard=2.14.0
- bioconda::gatk=3.8
- pip:
  - pysam==0.11
  - multiqc==0.9
